apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace | default "default" | lower }}
  labels:
    app: {{ .Release.Name }}-app
data:
{{- toYaml .Values.configMap | nindent 2 }}
{{- end }}