apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace | default "default" | lower }}
  labels:
    app: {{ .Release.Name }}-app
data:
  {{- toYaml .Values.configMap | nindent 2 }}
