apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace | default "default" | lower }}
spec:
  backend:
    serviceName: {{ .Realese.Name }}-service
    servicePort: {{ .Values.ingress.servicePort }}